const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const base=process.env.PIZZA_LAB_URL || 'http://127.0.0.1:8765/';
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE || undefined,headless:true});
 const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});
 await context.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort());
 const page=await context.newPage(); const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 page.on('dialog',d=>d.accept());
 await page.goto(base);
 await page.waitForSelector('#target-balls');
 assert.equal(await page.locator('#sync-label').innerText(),'solo locale');
 await page.fill('#target-balls','10'); await page.getByRole('button',{name:'Calcola ricetta',exact:true}).click();
 await page.waitForSelector('#save-panel:not(.hidden)');
 await page.fill('#save-ready-hours','0'); await page.click('#btn-save');
 await page.waitForFunction(()=>document.querySelector('#btn-save').textContent.includes('Salvato'));
 await page.click('[data-section=frigo]'); assert.equal(await page.locator('.frigo-total-num').innerText(),'10');
 await page.getByRole('button',{name:'Consumo / scarto'}).click();
 await page.fill('#move-qty','3'); await page.selectOption('#move-kind','scarto'); await page.fill('#move-note','Prova isolata'); await page.click('#move-save');
 await page.waitForFunction(()=>document.querySelector('.frigo-total-num').textContent==='7');
 await page.getByRole('button',{name:'Annulla',exact:true}).last().click();
 await page.waitForFunction(()=>document.querySelector('.frigo-total-num').textContent==='10');
 await page.click('[data-section=piano]');
 const serviceDay=await page.evaluate(()=>dateStr(new Date(Date.now()+86400000)));
 await page.fill('#plan-date',serviceDay); await page.locator('#plan-date').dispatchEvent('change');
 await page.fill('#plan-solina','20'); await page.locator('#plan-solina').blur();
 await page.waitForFunction(()=>document.querySelector('.plan-total b').textContent==='10');
 await page.click('[data-section=magazzino]'); await page.fill('#stock-delta-solina','25'); await page.fill('#stock-min-solina','5');
 await page.locator('.inventory-row').filter({has:page.locator('#stock-delta-solina')}).getByRole('button',{name:'Attiva e registra scorta'}).click();
 await page.waitForFunction(()=>document.querySelector('#stock-delta-solina').value==='');
 await page.click('[data-section=storico]'); await page.getByRole('button',{name:'Scheda produzione',exact:true}).click(); await page.waitForSelector('#modal-production');
 await page.getByRole('button',{name:'Chiudi',exact:true}).click();
 await page.click('[data-section=strumenti]');
 for(const section of ['ricette','piano','magazzino','frigo','storico']) { await page.click(`[data-section=${section}]`); const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1); assert.equal(overflow,false,`horizontal overflow ${section}`); }
 await page.reload(); await page.waitForSelector('#target-balls'); await page.click('[data-section=frigo]'); assert.equal(await page.locator('.frigo-total-num').innerText(),'10');
 assert.deepEqual(errors,[]); console.log('PASS browser: calculation, production, waste, undo, plan, inventory, archived sheet, navigation, mobile width, reload persistence');
 // Presets use a picker; deletion is a separate, recoverable flow.
 await page.click('[data-section=ricette]');
 const originalDose=await page.locator('#ing-solina').inputValue();
 await page.getByRole('button',{name:'💾 Salva preset',exact:true}).click();
 await page.fill('#preset-name','Preset verifica');
 await page.locator('#preset-dialog').getByRole('button',{name:'Salva preset',exact:true}).click();
 await page.waitForSelector('#preset-dialog',{state:'detached'});
 await page.fill('#ing-solina','9');
 await page.click('.preset-selector');
 await page.fill('#preset-search','Preset verifica');
 assert.equal(await page.locator('.preset-item').count(),1);
 assert.equal(await page.locator('#preset-dialog').getByRole('button',{name:/Sposta nel cestino/}).count(),0);
 await page.getByRole('button',{name:'Applica Preset verifica',exact:true}).click();
 await page.waitForSelector('#preset-dialog',{state:'detached'});
 assert.equal(await page.locator('#ing-solina').inputValue(),originalDose);
 await page.click('.preset-selector');
 await page.getByRole('button',{name:'Gestisci Preset verifica',exact:true}).click();
 await page.fill('#preset-name','Preset rinominato');
 await page.getByRole('button',{name:'Salva nome',exact:true}).click();
 await page.getByRole('button',{name:'Gestisci Preset rinominato',exact:true}).click();
 await page.getByRole('button',{name:'Sposta nel cestino…',exact:true}).click();
 assert.equal(await page.locator(':focus').innerText(),'Mantieni preset');
 await page.getByRole('button',{name:'Mantieni preset',exact:true}).click();
 await page.getByRole('button',{name:'Sposta nel cestino…',exact:true}).click();
 await page.getByRole('button',{name:'Sposta nel cestino',exact:true}).click();
 await page.getByRole('button',{name:'Cestino',exact:true}).click();
 assert.equal(await page.locator('.preset-item').count(),1);
 await page.getByRole('button',{name:'Ripristina',exact:true}).click();
 await page.getByRole('button',{name:'Salvati',exact:true}).click();
 assert.equal(await page.getByRole('button',{name:'Applica Preset rinominato',exact:true}).count(),1);
 await page.getByRole('button',{name:'Chiudi',exact:true}).click();
 await page.reload(); await page.waitForSelector('.preset-selector');
 await page.click('.preset-selector');
 assert.equal(await page.getByRole('button',{name:'Applica Preset rinominato',exact:true}).count(),1);
 console.log('PASS presets: save, search, apply, rename, safe cancellation, trash, restore, reload');
 await context.close();
 const offline=await browser.newContext();
 await offline.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort());
 const pwa=await offline.newPage(); pwa.on('dialog',d=>d.accept());
 await pwa.goto(base); await pwa.waitForSelector('#target-balls');
 await pwa.waitForFunction(()=>navigator.serviceWorker.controller);
 await offline.setOffline(true); await pwa.reload(); await pwa.waitForSelector('#target-balls');
 assert.equal(await pwa.locator('#sync-label').innerText(),'solo locale');
 await offline.close(); console.log('PASS PWA: complete shell starts offline');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
